### ISSUE TITLE
On `localize`s language detection strategy

### ISSUE THREAD

**Issue by mcjazzyfunky** [shoelace-style/localize#1]
Cool stuff - especially this "function as translation" thingy seems pretty smart :+1:
I know this issue comes quite early, anyway...

Two remarks on the "language detection strategy".

1. I think, empty lang attributes should be ignored, means `<div lang="">` should behave the same as `<div>`.

2. It may first sound like a good feature to introduce this `forceUpdate` function to make lang attribute changes partially (!!!) observable in shadow DOM, but you have to pay a really high price just for a little bit more flexibility (that may not even be really necessary - at least it will not be often used, I'm quite sure).
  
    Let's call the current `localize` language detection strategy "shadow-included" strategy, while an alternative and way  easier strategy to  just ignore all lang attributes in shadow dom shall be called "shadow-excluded" strategy.

    With the "shadow-included" strategy
  
    ```html
     We are in shadow DOM (!) using "shadow-included" strategy.
        
     The date pickers will be shown in French, but if the `lang` attribute 
     of that `div` element changes the date pickers
     will still use the `fr` language.
     This seems trivial ... but see the next example ...
     
    <div lang="fr">
      <sl-date-picker></sl-date-picker>
      <sl-date-picker></sl-date-picker>
    </div>
    ```
    
    ```html
     We are in shadow DOM (!) using "shadow-included" strategy.
      
     The date pickers will be shown in French ... but what will happen
     if the `lang` attribute of that `horizontal-layout` element changes???
     Will the date pickers also change the language accordingly???
     The answer is: We just don't know ... at least as long as we do not know
     details about that `horizontal-layout` component ... will it us SL's "forceUpdate"
     function internally or not??? Why should a non-localizable simple layout
     component even care about localization issues?!?
     
    <horizontal-layout lang="fr">
      <sl-date-picker></sl-date-picker>
      <sl-date-picker></sl-date-picker>
    </horizontal-layout>
    ```
  
 Disadvantages of the "shadow-included" language detection strategy:

- Every single component that has slots and wants to support SL's "shadow-included" strategy has to observe it's own `lang` attribute and call the SL specific `forceUpdate` function. That means that SL "compatible" components are first-class citizens while all other components are just second-class. And why should a basically SL independent component add a dependency to SL just to become friend with SL's language detection strategy?
- It's not always easily recognizable which custom elements support the "shadow-included" strategy and which are not.
- More work for each single component with slot (at least more than "zero work" as with the "shadow-excluded" strategy)

The advantages of the "shadow-excluded" language detection strategy (the only disadvantage is "a bit less flexibility"):

- There's only one simple rule: "All lang attributes in shadow DOM will be ignored .. without any exceptions".
- It is always 100% predictable if and when `lang` aware components will change their language.
- With the "shadow-excluded" strategy not a single component (not even in SL core) has to observe its own `lang` attribute - the observation of the `lang`attribute will be taken over out of the box by `localize`'s own global mutation observer.
- Different component libraries can use the same "shadow-excluded" language detection strategy without sharing an special API or knowing each other. All custom elements (and also all built-in elements) are first-class citizens with the "shadow-excluded" strategy.

Maybe it would first be a good idea to find out for what real-world use cases a "shadow-included" strategy would be a total must-have while a "shadow-excluded" strategy would be a complete deal breaker.

**Comment by claviska** [comment]
The idea behind the current approach is that `lang` cascades down, and that includes elements in shadow roots. Unless a language is explicitly set, it's safe to assume the language wrapped around the custom element is the intended language.

Note that this is already an edge case, as most apps only use one language per page.

I realize there's a requirement for third-party components to use `forceUpdate()` if they choose to localize with this approach. That's a necessary trade off since there's simply no way to reliably observe every shadow root. Furthermore, `slotchange` isn't sufficient because it only emits when slotted elements change, not their children.

If third-party components choose to do this, they're responsible for the implementation. They can do it with a reactive property, a mutation observer, or whatever mechanism they want because the function is available. The important thing is that the responsibility gets moved _away from the consumer_ so all they need to do is set `lang` and import the desired translation(s).

> Every single component that has slots and wants to support SL's "shadow-included" strategy has to observe it's own lang attribute and call the SL specific forceUpdate function.

Slotted content shouldn't be translated with this tool. That content should be translated at the framework level and slotted in to the component, keeping it in the light DOM.

If you're building components in such a way that slotted content ends up in another component's shadow root, you're probably building an app with web components. In that case, you should look into a proper app-level localization solution such as [@lit/localize](https://www.npmjs.com/package/@lit/localize) or [i18next](https://www.i18next.com/).

I consider slotted content outside the scope of a component-level localization library.

> That means that SL "compatible" components are first-class citizens while all other components are just second-class.

Yes, exactly. If you're developing sister components that follow Shoelace patterns and use this localization technique, they will all work the same way. Other components that do not adhere to these patterns are responsible for their own handling. It shouldn't be up to this library to solve localization for rogue components.

But, since developers have opinions, that's why I chose to use the standard `lang` attribute:

> The lang global attribute helps define the language of an element ([source](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang))

It's semantically incorrect for a custom element to _not_ localize based on `lang`, so whatever mechanism other components use for localization should consider this.

**Comment by mcjazzyfunky** [comment]
Regarding 1.

> If the attribute value is the empty string (lang=""), the language is set to unknown; if the language tag is not valid according to BCP47, it is set to invalid.

Oh yeah, you're right, that's convincing. Thanks for the info.

---

Regarding 2.
Yet quite a high price to pay. Still wondering which real-world use cases really need this absolutely.

Thanks @claviska ... I will close this issue then.

**Comment by claviska** [comment]
This is another one of those things that feels like a gap in the platform. One day, I hope we can rely on a standard, perhaps`Intl`, instead of rolling localization ourselves.
