### ISSUE TITLE
Customizing base localization functionality

### ISSUE THREAD

**Issue by mcjazzyfunky** [shoelace-style/localize#3]
Note: The following is only relevant for app developers (app level), not for component developers (library level)!

To make `Localize` (and hence `Sholace`) more flexible and a bit more enterprise-ready it is an absolute must-have to make base localization functions customizable. Many developers know it: If you work on a big multi-country project for a global enterprise there's is often at least one :wink: country division that wants some non-standard behavior for some I18n aspects. Or an enterprise wants a unified country-independent behavior for a certain aspect of I18n in their internal apps.
An everyday customization requirement is for example to modify how `Localizer` will handle unavailable translations. I personally use to have (for good reasons) slightly different "unavailable translation" strategies on DEV, TEST and PROD system or in certain stages of the development lifecycle. Normally things like that are solved in a different abstraction level (for example when using some kind of dependency injection), but Shoelace will not have any i18n abstraction levels, so it might be an option to add the customization capability in `Localizer` itself.

To be clear, this is currently only about the three functions `formatNumber`, `formatDate` and `translate`. More functions will follow in future, but I guess there will never be more than maybe two handfuls of base functions that must be customizable.

I personally don't care how exactly this will be implemented. The only really important requirement is that such fundamental I18n functions are indeed customizable.

An example (but this is just an example, implement everything completely different if you want):
There could be a function `initI18n` that can only be invoked one single time (after start of the app) and it has to be called BEFORE any localization function will be called (otherwise an error will be thrown). This is to make sure that the relevant localization functions stay pure (in mathematical sense - `translate` is an exception) and will not change their behavior after initially set.

<details>
<summary>
  Click me to see code
</summary>

```ts
initI18n({
  // ... more parameters may follow in future ...

  // this is the important part (self = customized behavior, base = base behavior).
  // Details are not that imporant here, as this is only an example
  customize: (self, base)  => ({
    translate(locale, key, ...args) {
       ...
    },

    formatDate(lang, date, options?) {
      // this might not be customized very often (in my working life, I had such a customization
      // requirement only once)
      ...
    }
  })
```
</details>

A corresponding implementation will not be a big challenge but it will produce some additional code (I gave it a try: Needed 140 lines of code for a initial never tested version .. for comparison: `index.ts` has currently only 101 lines). Maybe an additional package `@shoelace-style/localizer/customize` or whatever could be an option.

If - for whatever reasons - this task needs more thinking time and will not be implemented soon, a temporary workaround could be to make those `Localize` functions monkey patchable - not as official "feature", also not documented, but at least for R&D at own risk.

<details>
<summary>
Something like the following could do the trick to make things monkey patchable
</summary>

```ts

export { i18n as __internal__ }

export function formatDate(lang: string, date: Date | string, options?: Intl.DateTimeFormatOptions) {
  return i18n.formatDate(lang, date, options);
}

export function formatNumber(lang: string, number: number | string, options?: Intl.NumberFormatOptions) {
  return i18n.formatNumber(lang, number, options);
}

function translate<K extends keyof Translation>(lang: string, key: K, ...args: FunctionParams<Translation[K]>) {
  return i18n.translate(lang, key, ...args);
}

const i18n = {
  formatDate(lang: string, date: Date | string, options?: Intl.DateTimeFormatOptions) {
    date = new Date(date);
    return new Intl.DateTimeFormat(lang, options).format(date);
  },
  
  formatNumber(lang: string, number: number | string, options?: Intl.NumberFormatOptions) {
    number = Number(number);
    return isNaN(number) ? '' : new Intl.NumberFormat(lang, options).format(number);
  },
  
  translate<K extends keyof Translation>(lang: string, key: K, ...args: FunctionParams<Translation[K]>) {
    ... 
  }
}
```
</details>

**Comment by claviska** [comment]
> To make Localize (and hence Sholace) more flexible and a bit more enterprise-ready it is an absolute must-have to make base localization functions customizable. 

I think there's a misunderstanding about the scope of the library. It's not intended to be used at a high level or for robust translations. While it can be consumed and extended by third-party components, it doesn't have to be and it probably doesn't make sense to do so in most cases.

To reiterate, the idea is to provide a thin localization shim that remains internal to a component library and relies only on standard platform features. The end user only needs to do two things:

1. Import the desired translation(s)
2. Set the `lang` attribute

> this is currently only about the three functions formatNumber, formatDate and translate

It's only about one, since `formatDate` and `formatNumber` wrap the `Intl` API. You really can't have a missing or invalid term in those because the browse will throw an error.

> An everyday customization requirement is for example to modify how Localizer will handle unavailable translations.

Are you talking about unavailable _translations_ or unavailable _terms_? I'm assuming the latter, as its up to the consumer to import the translations their app will support. The fallback will still allow things to work if someone uses an unsupported value for `lang`.

Currently, if a term or its fallback can't be found, the translation key is output and [a console error](https://github.com/shoelace-style/localize/blob/main/src/index.ts#L62) is thrown. Your testing strategy should include all supported languages. I would suggest attaching a spy to `console.error` to listen for missing terms. (If you want to test without a fallback, only load the target translation.)

Will that suffice for your use case?

For component devs, it's already more complicated than I'd like it to be in terms of setup. I don't see any advantage in adding an initialization step that a majority of users may not care about. If anything, it should be optional.

> If - for whatever reasons - this task needs more thinking time and will not be implemented soon, a temporary workaround could be to make those Localize functions monkey patchable - not as official "feature", also not documented

There's already an example in the readme about wrapping the `translate()` function for strong typings. I'm not sure how you'd tap into it for missing terms, though. That function can't throw an error because it will block rendering (hence the `console.error` warning instead). I think it's fairly common for the translation key to be output, which is the current behavior.

I'm not sure what else you're looking for here.

**Comment by mcjazzyfunky** [comment]
Frankly, I'm really not sure why this very unusual dogmatic approach of hard-coding stuff without the ability to customize is so extreeeemely important to you.
`Localize` is currently basically saying, that there's only one useful strategy for each localization concern, one strategy only - if someone wants different strategies then `Localize` says: "This is neither wanted nor needed. I do not care about your requirements. Your requirements are useless. The hard-coded strategies in `Localize` are the only reasonable and useful`".
Why do we even discuss about whether hard-coded strategies are a good thing or should avoided?

If someone doesn't want [that](https://github.com/shoelace-style/localize/blob/a32cf4229f9f8892e2de5634b2606d7b2fb45ec1/src/index.ts#L63) on live system, why does `Localize`have to force her?

>  I think it's fairly common for the translation key to be output, which is the current behavior.

Allowing only "the common behavior" is dogmatic.

If someone wants only ONE error log entry per missing translation instead of the hard-coded strategy in `Localize` to error log each single occurrence, why do `Localize` want to prevent this or force her to monkey patch `console.error` or do other crazy stuff?

If someone does not want to use `Intl` directly but maybe want to use her own fancy i18n library which itself is based on `Intl` but happens to be perfectly customizable with a high flexibility of altering the standard behavior if needed. Why does `Localize` not allow that? What's so important about the currently two `Intl` function calls in `Localize` that overriding this hard-coded `Intl` calls is absolutely forbidden and therefore not possible?

In almost all cases I consider [this](https://github.com/shoelace-style/localize/blob/main/src/index.ts#L59-L60) an error case. Currently I am not able to handle this as an error. Why?

I'm planning to use SL for admin panels. At least for my personal admin panels I want to use the ISO date format independent of the locale. Is that currently possible without any hacks? I don't think so, am I wrong?

Quite soon there will be further requirements for `Localize` like`getFirstDayOfWeek`, `getCalendarDay`, etc. and even `parseNumber` and `parseDate`. How do you plan to handle them? An answer like "Not in the scope of this library" will not be very helpful ... with some way of customization you'll easily find "good enough" solutions for that, but I have no idea how these requirements will be satisfied with a few dozen lines of code without allowing customization.

> I don't see any advantage in adding an initialization step that a majority of users may not care about. If anything, it should be optional.

Of course, it will be optional.

> [...] for strong typings

Not everybody uses TypeScript.

I'm not asking for a different architectural paradigms here any longer. The only thing I am asking for is: Please allow one single function `init18n` or whatever name you like in a separate package `@shoelace-style/localize/customize` or a different file `@shoelace-style/localize/dist/customize.js` or whatever, I don't mind, and allow the base functions `formatDate`, `formatNumber`, `translate` (a few others will follow in future) to be overridden. Things will become so much more flexible. Again: Since when are hard-coded, non-exchangeable dogmatic strategies considered good solutions?

**Comment by claviska** [comment]
> Frankly, I'm really not sure why this very unusual dogmatic approach of hard-coding stuff without the ability to customize is so extreeeemely important to you.

I try not to be dismissive, but there's a point where it becomes mentally taxing to endure constant hypotheticals and what-if scenarios that are either unlikely or out of the project's scope. Rather than ignore issues, I always try to respond with what I was thinking and what I believe is right for the project. Maybe I should stop doing that.

Many of the issues you've posted are over-engineering what is currently a very simple concept. What I'd like to see before jumping in and doing all of that work — which quite possibly will only ever benefit you — is a collection of feedback from various users who have experimented with the library and ran into real world problems. Those are things that are worth solving. Prematurely optimizing things because you might need them is not.

This solves my immediate need.

> Quite soon there will be further requirements for Localize like `getFirstDayOfWeek`, `getCalendarDay`, etc. and even `parseNumber` and `parseDate`. How do you plan to handle them? An answer like "Not in the scope of this library" will not be very helpful

I don't have a need for them and don't foresee any of those being a requirement. If you do, consider forking the library and adding them yourself or writing your own from scratch. Better yet, use a proper i18n solution. This isn't intended to be that.

As I've stated before, this _experimental_ library has a very limited scope and has been presented for feedback. It has not been implemented in Shoelace or anywhere else that I'm aware of. Yes, you could expand this concept. Yes, you could make everything in it customizable. Is it worth the effort to me right now? No. [But code can change.](https://www.abeautifulsite.net/posts/code-can-change/)

Note that I would be much more apt to entertain a clean PR (as long as it's inline with the library's scope) than a multitude of issues demanding features.

> To make Localize (and hence Sholace) more flexible and a bit more enterprise-ready it is an absolute must-have to make base localization functions customizable. Many developers know it: If you work on a big multi-country project for a global enterprise there's is often at least one 😉 country division that wants some non-standard behavior for some I18n aspects.

This is conjecture. If they have that need, they should use a proper i18n library. My goal is to localize component internals, not to provide a full i18n solution.

All I really want to know from users at this point is, does the concept of using `lang` and creating/importing translation files work well for other component library authors? From there, we'll evolve it and address issues that are actually issues.

---

That said, it probably does make sense to customize the behavior of terms that are missing from translations. My last response included an uncertainty:

> I'm not sure how you'd tap into it for missing terms, though. That function can't throw an error because it will block rendering (hence the console.error warning instead).

I didn't say I was opposed to it. I'm just not sure the best way to do it at this point and I don't feel that users should have to call an init function to use the library. I'll think on it.

**Comment by mcjazzyfunky** [comment]
Okay, thanks for your response and help and all that discussion, which helped me (and hopefully others) a lot to get a better view on the topic (for example your comments in #1 were 100% convincing and really helpful).
I will close this issue now, as it is obvious that I've already stressed you at a level that is unacceptable.
I'm deeply sorry for that, that was never my intention, I just wanted to share ideas and use cases of my working life to help making things more flexible.

Maybe I may ask you to make sure for Sholace that the `Localize` library or its successors  always stays exchangeable on build/bundler level if anyone needs to customize it for her app (I guess, you would have done this anyway).

<details>
<summary>[click me] Please find here a last tiny suggestion :wink:</summary>
<br>
Maybe it makes sense to replace https://github.com/shoelace-style/localize/blob/a32cf4229f9f8892e2de5634b2606d7b2fb45ec1/src/index.ts#L59-L64
 
  ```ts
  } else if (fallback && fallback[key]) {
    term = fallback[key];
  } else {
    console.error(`Cannot find "${key}" to translate.`);
    return key;
  }
  ```
  
  with this
  
  ```ts
  } else {
    console.error(`Cannot find "${key}" to translate.`);

    if (fallback && fallback[key]) {
      term = fallback[key];
    } else {
      return key;
    }
  }
  ```
</details>

So, like said: Thank you very much for sharing your ideas and opinions. I will close this issue then....
