### ISSUE TITLE
Why does function `registerTranslation` not merge translations with same $code?

### ISSUE THREAD

**Issue by xdev1** [shoelace-style/localize#7]
Let's assume you are developing an app that is using `@shoelace-style/shoelace` and two completely independent third-party component libraries `@author1/some-datepicker` and `@author2/some-datagrid`.
All three are using `@shoelace-style/localize` for localization.
All three have their own translation files for locale `en`.

Function `registerTranslation` is not merging translations if several translations with the same `$code` value are provided, means already given translations will be completely overridden and translation information will get lost.

The logical conclusion is that either it may not be a good idea that `registerTranslation` is not merging given translations with the same `$code` value, or that libraries NEVER should call `registerTranslation`, only applications should call `registerTranslation` and merge given library translations by themself.

To make a long story short: I claim that `registerTranslation` should really merge given translations with same `$code` and that this `fallback: Translation` variable should be replaced by `fallbackCode: string`.

**Comment by claviska** [comment]
Good suggestion. As you stated, `registerTranslation()` will currently overwrite any existing translation with the same code. It would be convenient to have an official way to extend translations.

Currently, the only way to do this at runtime is to import the translation and do this:

```js
import translation from '../en.js';

translation.newTerm = 'New Term';
translation.complexTerm = val => `The value is `${val}`;
```

While this works, it's not an ideal solution for extending because you need to know where the translation file lives to import it and, if it's strongly typed, you'll need to re-export a new type and keep track of this each time you extend the translation.

My only questions are:

- Should this be done in `registerTranslation()` or in a new method, e.g. `mergeTranslation()`?
- What does this mean for users of strongly typed translations? i.e. if I've typed all my terms, what does it look like to combine them in a way that TypeScript still understands?

**Comment by xdev1** [comment]
This is not really tested properly, but I think something like this should (hopefully :wink:) work (rest remains as is):

```ts
//
// Registers one or more translations
//
export function registerTranslation(...translation: Translation[]) {
  translation.forEach(t => {
    const code = t.$code.toLowerCase();

    if (translations.has(code)) {
      Object.assign(translations.get(code), t);
    } else {
      const t2 = { ...t };
      translations.set(code, t2);

      // The first translation that's registered is the fallback
      if (!fallback) {
        fallback = t2;
      }
    }
  });

  update();
}
````

**Comment by xdev1** [comment]
@claviska Thanks for altering function `registerTranslation` to use "merging" instead of "overwriting".

I'll close this isse then.
