### ISSUE TITLE
LocalizeController should also work with other webcomponent libraries, not only with Lit

### ISSUE THREAD

**Issue by xdev1** [shoelace-style/localize#8]
Currently `LocalizeController` is only working if you're using a webcomponent library that's based on Lit's `ReactiveController` model (I guess, there aren't any other than `Lit` itself at the moment).
This limitation is not necessary. Class `LocalizeController` can be modified to also support other webcomponent libraries that have features similar to `addController`.
I'll prepare a PR.

**Comment by claviska** [comment]
Just a heads up that I won’t accept a PR to remove Reactive Controller compatibility. RCs are still very young, but one of their most promising features (and part of their author’s mission) is to make them as generic as possible so other libraries and frameworks will opt into the format.

I’m intentionally promoting RCs because they aim to be open and nonproprietary and I happen to use this pattern in other libraries as well. Removing it from this utility is counterproductive to me in both advocating for the success of Reactive Controllers and maintaining consistency with my other codebases.

If you disagree with that statement, you have my blessing to fork the project.

Otherwise, I encourage you and others to either contribute to libraries that don’t yet support RCs or perhaps write an adapter for them, which has a much higher value since more code can be reused by more people in more places with more ease — and that would be a big win for everybody.
